[toolchain]
anchor_version = "0.30.1"  # `anchor-cli` version to use(requires `avm`)

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_ticketing = "Ho5cw5Vk1yaQJKqaVyU4KPvXvCThJDRaFL19Hgx6yrp6"

[programs.devnet]
nft_ticketing = "Ho5cw5Vk1yaQJKqaVyU4KPvXvCThJDRaFL19Hgx6yrp6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"                 # The cluster used for all commands.
wallet = "~/.config/solana/id.json"  # The keypair used for all commands.

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
